import type { ColumnDef } from "@tanstack/react-table";
import Link from "next/link";
import { ArrowRightIcon, ShieldAlertIcon } from "lucide-react";

import { DataTable } from "@/components/admin/DataTable";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";

import type { DashboardRecentThreat } from "./DashboardLogic";

type RecentHighPriorityThreatsProps = {
  threats: DashboardRecentThreat[];
};

export function RecentHighPriorityThreats({
  threats,
}: RecentHighPriorityThreatsProps) {
  const columns: ColumnDef<DashboardRecentThreat>[] = [
    {
      id: "index",
      header: "#",
      cell: ({ row }) => (
        <span className="font-medium text-muted-foreground">{row.index + 1}</span>
      ),
    },
    {
      accessorKey: "eventType",
      header: "Event Type",
      cell: ({ row }) => (
        <span className="font-medium text-foreground">
          {row.original.eventType}
        </span>
      ),
    },
    {
      accessorKey: "source",
      header: "Source",
      cell: ({ row }) => (
        <span className="text-muted-foreground">{row.original.source}</span>
      ),
    },
    {
      accessorKey: "indicator",
      header: "Indicator",
      cell: ({ row }) => (
        <span className="text-muted-foreground">{row.original.indicator}</span>
      ),
    },
    {
      accessorKey: "priorityLabel",
      header: "Priority",
      cell: ({ row }) => (
        <Badge
          className={`rounded-full px-2.5 py-0.5 ${getPriorityBadgeClassName(
            row.original.priority,
          )}`}
        >
          {row.original.priorityLabel}
        </Badge>
      ),
    },
    {
      accessorKey: "score",
      header: "Score",
      cell: ({ row }) => (
        <span className="whitespace-nowrap font-medium text-primary">
          {row.original.score}
        </span>
      ),
    },
    {
      accessorKey: "statusLabel",
      header: "Status",
      cell: ({ row }) => (
        <Badge
          className={`rounded-full px-2.5 py-0.5 ${getStatusBadgeClassName(
            row.original.status,
          )}`}
        >
          {row.original.statusLabel}
        </Badge>
      ),
    },
    {
      accessorKey: "detectedAt",
      header: "Detected At",
      cell: ({ row }) => (
        <span className="whitespace-nowrap text-primary/80">
          {row.original.detectedAt}
        </span>
      ),
    },
  ];

  return (
    <section className="grid gap-4">
      <DataTable
        actions={
          <Button asChild className="h-10 rounded-md" type="button">
            <Link href="/admin/threat-events">
              View all threats
              <ArrowRightIcon className="size-4" />
            </Link>
          </Button>
        }
        columns={columns}
        data={threats}
        description="Latest high and critical priority threat events generated by correlation and scoring."
        emptyMessage="No high-priority threats yet. High and critical priority threat events will appear here after correlation and scoring."
        emptyStateIcon={<ShieldAlertIcon className="size-5" />}
        pageSize={10}
        title="Recent high-priority threats"
      />
    </section>
  );
}

function getPriorityBadgeClassName(priority: DashboardRecentThreat["priority"]) {
  if (priority === "critical") {
    return "bg-red-50 text-red-700";
  }

  if (priority === "high") {
    return "bg-amber-50 text-amber-700";
  }

  if (priority === "medium") {
    return "bg-yellow-50 text-yellow-700";
  }

  return "bg-emerald-50 text-emerald-700";
}

function getStatusBadgeClassName(status: DashboardRecentThreat["status"]) {
  if (status === "open") {
    return "bg-red-50 text-red-700";
  }

  if (status === "investigating") {
    return "bg-amber-50 text-amber-700";
  }

  if (status === "resolved") {
    return "bg-emerald-50 text-emerald-700";
  }

  return "bg-slate-100 text-slate-700";
}
